baseURL = "https://jonezy.art/"
languageCode = "en-us"
title = "Jonezy Art"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "jonezy"
  description = "Featuring "
  message = ""
  hideAutoMenu = false

[[menu.main]]
  name = "Instagram"
  url = "https://instagram.com/jonezyart"

[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/jonezyart"

[social]
  facebook = "https://facebook.com/jonezyart"
  twitter = "https://twitter.com/jonezyart"
  instagram = "https://instagram.com/jonezyart"
  linkedin = ""